//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpcaHomeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alojamento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alojamento()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int ID { get; set; }
        public int ProprietárioID { get; set; }
        public int EstudanteID { get; set; }
        public int AgenteImobiliariaID { get; set; }
        public int LocalizaçãoID { get; set; }
        public string disponibilidade { get; set; }
        public string informacoes { get; set; }
        public string restricoes { get; set; }
        public Nullable<int> avaliacao { get; set; }
        public string historico { get; set; }
    
        public virtual AgenteImobiliaria AgenteImobiliaria { get; set; }
        public virtual Estudante Estudante { get; set; }
        public virtual Proprietario Proprietario { get; set; }
        public virtual Localização Localização { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
