//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpcaHomeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudante()
        {
            this.Alojamento = new HashSet<Alojamento>();
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int ID { get; set; }
        public int UtilizadorID { get; set; }
        public string universidade { get; set; }
        public string curso { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> numeroCC { get; set; }
        public Nullable<int> dataNasc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alojamento> Alojamento { get; set; }
        public virtual Utilizador Utilizador { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
