//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IpcaHomeModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localização
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Localização()
        {
            this.Alojamento = new HashSet<Alojamento>();
        }
    
        public int ID { get; set; }
        public string rua { get; set; }
        public Nullable<int> porta { get; set; }
        public string localidade { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Alojamento> Alojamento { get; set; }
    }
}
